baseURL = "https://blog.kawaguchi-design.com/"
languageCode = "ja"
title = "kawaguchi-design-blog"
theme = "noteworthy"

[params]
    # Programming
    github = "https://github.com/kawaguchi1102"
[params.assest]
    customCSS = ["/css/custom.css"]
